my_file = open("file02.txt", "r", encoding="UTF-8")
content = my_file.read()
print(f"Содержимое файла: \n {content}")
my_file = open("file02.txt", "r")
content = my_file.readlines()
print(f"Количество строк в файле - {len(content)}")
my_file = open("file02.txt", "r")
content = my_file.readlines()
for i in range(len(content)):
    print(f"Окличество символов строки №{i + 1}: {len(content[i])}")
my_file = open("file02.txt", "r")
content = my_file.read()
content = content.split()
print(f"Общее количество слов - {len(content)}")
my_file.close()
